# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05be896f4bfd52ba3e5714634c026b2d07030ff119f46d71480c24f4d8a9bcaf31a7bc184ca6d30be40cdf18192d7493406377573a54a61c187695c34bf4b302

test:
  secret_key_base: 0e2cb232eeaeb790bdbfca10484f2ab1bba331d0bb1658c1f8891ba5f2c6432d10684f1c66427b557429e81496ece4dee107026ba54bd1cdf611c38542f0672d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
